version: "3"
services:
    base:
        build: .
        image: tbrlpld/log100days:latest
        ports: 
            - "127.0.0.1:5000:5000"
        command: hypercorn --workers 3 --bind 0:5000 log100days:app